name: Build Docker Image and Upload TAR

on:
  workflow_dispatch:

jobs:
  build-and-upload-tar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Dockerfile dynamically
        run: |
          cat <<EOF > Dockerfile
          FROM xinference:latest
          RUN pip install --no-cache-dir --upgrade transformers
          EOF

      - name: Build Docker image
        run: |
          docker build -t xinference:transformers-upgraded .

      - name: Save image to tar
        run: |
          docker save xinference:transformers-upgraded -o xinference_transformers_upgraded.tar

      - name: Upload image tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: xinference-transformers-tar
          path: xinference_transformers_upgraded.tar
