name: Save ollama/ollama:cuda Docker Image

on:
  workflow_dispatch:  # 手动触发，也可以换成 schedule 或 push

jobs:
  save-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (required by actions/upload-artifact)
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull ollama/ollama:cuda image
        run: docker pull ollama/ollama:cuda

      - name: Save image to tarball
        run: docker save ollama/ollama:cuda -o ollama-cuda.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ollama-cuda-image
          path: ollama-cuda.tar
