name: Query Latest Pause Image Version

on:
  workflow_dispatch:

jobs:
  query-pause-version:
    runs-on: ubuntu-latest
    steps:
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: List tags for pause image
        run: |
          skopeo list-tags docker://registry.k8s.io/pause | jq .
