name: Inline Docker Build with vLLM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image inline
        run: |
          docker build -t vllm-api-server:latest - <<EOF
          FROM nvcr.io/nvidia/pytorch:25.04-py3

          ARG VLLM_VERSION=0.8.5.post1

          RUN apt-get update && apt-get install -y git wget curl && \
              rm -rf /var/lib/apt/lists/*

          RUN pip install --upgrade pip setuptools wheel

          RUN wget https://github.com/vllm-project/vllm/releases/download/v\${VLLM_VERSION}/vllm-\${VLLM_VERSION}.tar.gz && \
              pip install vllm-\${VLLM_VERSION}.tar.gz --no-deps && \
              rm vllm-\${VLLM_VERSION}.tar.gz

          WORKDIR /workspace
          EXPOSE 8000
          CMD ["python3", "-m", "vllm.entrypoints.openai.api_server"]
          EOF

      - name: Check built image
        run: docker images | grep vllm-api-server
