name: Save Docker Images to Tar

on:
  workflow_dispatch:

jobs:
  save-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker images
        run: |
          while read image; do
            echo "Pulling $image"
            docker pull "$image"
          done < images.txt

      - name: Save Docker images to TAR
        run: |
          mkdir -p docker-images
          docker save $(cat images.txt | tr '\n' ' ') -o docker-images/kubernetes-images.tar

      - name: Upload TAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: save-images-tar
          path: docker-images/kubernetes-images.tar
