name: Pull Kubernetes Images v1.33.2

on:
  workflow_dispatch:

jobs:
  pull-images:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Pull and tag Kubernetes v1.33.2 images
        run: |
          REGISTRY=registry.aliyuncs.com/google_containers
          VERSION=v1.33.2
          ETCD_VERSION=3.5.21-0
          COREDNS_VERSION=v1.12.0
          PAUSE_VERSION=3.10

          IMAGES=(
            kube-apiserver
            kube-controller-manager
            kube-scheduler
            kube-proxy
          )

          for image in "${IMAGES[@]}"; do
            docker pull $REGISTRY/$image:$VERSION
          done

          docker pull $REGISTRY/etcd:$ETCD_VERSION
          docker pull $REGISTRY/coredns:$COREDNS_VERSION
          docker pull $REGISTRY/pause:$PAUSE_VERSION

          echo "✅ All images pulled successfully"
