name: Build PHP 7.3.33 on ARM64 emulator

on:
  workflow_dispatch:

jobs:
  build-php:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU for ARM64 emulation
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Use ARM64 Ubuntu container
        uses: docker://arm64v8/ubuntu:20.04
        with:
          options: --privileged

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export TZ=Etc/UTC
          apt-get update && apt-get install -y \
            build-essential autoconf bison re2c curl \
            libxml2-dev libsqlite3-dev libcurl4-openssl-dev libjpeg-dev \
            libpng-dev libwebp-dev libfreetype6-dev libzip-dev libonig-dev \
            libssl-dev libreadline-dev pkg-config libmysqlclient-dev \
            libxslt1-dev libpq-dev libicu-dev file

      - name: Download and extract PHP
        run: |
          curl -sSL https://www.php.net/distributions/php-7.3.33.tar.gz | tar -xz

      - name: Configure PHP
        working-directory: php-7.3.33
        run: |
          ./buildconf --force
          ./configure --prefix=/php-7.3.33 \
            --with-config-file-path=/php-7.3.33/etc \
            --enable-fpm \
            --with-fpm-user=www-data \
            --with-fpm-group=www-data \
            --enable-mbstring \
            --enable-mysqlnd \
            --with-curl \
            --with-openssl \
            --with-zlib \
            --with-pdo-mysql \
            --enable-soap \
            --enable-intl \
            --with-xsl \
            --enable-bcmath \
            --with-gettext \
            --with-readline

      - name: Compile PHP (no install)
        working-directory: php-7.3.33
        run: make -j$(nproc)

      - name: Upload build dir
        uses: actions/upload-artifact@v4
        with:
          name: php-7.3.33-build
          path: php-7.3.33
