name: Save Docker Images to Tar

on:
  workflow_dispatch:

jobs:
  save-images:
    runs-on: ubuntu-latest

    steps:
      - name: Create image list
        run: |
          mkdir -p docker-images
          cat <<EOF > images.txt
docker.m.daocloud.io/calico/apiserver:v3.30.1
docker.m.daocloud.io/calico/cni:v3.30.1
docker.m.daocloud.io/calico/csi:v3.30.1
docker.m.daocloud.io/calico/goldmane:v3.30.1
docker.m.daocloud.io/calico/kube-controllers:v3.30.1
docker.m.daocloud.io/calico/node-driver-registrar:v3.30.1
docker.m.daocloud.io/calico/node:v3.30.1
docker.m.daocloud.io/calico/pod2daemon-flexvol:v3.30.1
docker.m.daocloud.io/calico/typha:v3.30.1
docker.m.daocloud.io/calico/whisker-backend:v3.30.1
docker.m.daocloud.io/calico/whisker:v3.30.1
docker.m.daocloud.io/kubesphere/openelb-controller:v0.6.0
docker.m.daocloud.io/kubesphere/openelb-speaker:v0.6.0
docker.m.daocloud.io/kubesphere/kube-webhook-certgen:v1.1.1
docker.m.daocloud.io/longhornio/csi-attacher:v4.9.0
docker.m.daocloud.io/longhornio/csi-node-driver-registrar:v2.14.0
docker.m.daocloud.io/longhornio/csi-provisioner:v5.3.0
docker.m.daocloud.io/longhornio/csi-resizer:v1.13.2
docker.m.daocloud.io/longhornio/csi-snapshotter:v8.2.0
docker.m.daocloud.io/longhornio/livenessprobe:v2.16.0
docker.m.daocloud.io/longhornio/longhorn-engine:v1.8.2
docker.m.daocloud.io/longhornio/longhorn-instance-manager:v1.8.2
docker.m.daocloud.io/longhornio/longhorn-manager:v1.8.2
docker.m.daocloud.io/longhornio/longhorn-share-manager:v1.8.2
docker.m.daocloud.io/longhornio/longhorn-ui:v1.8.2
quay.m.daocloud.io/tigera/operator:v1.38.1
registry.aliyuncs.com/google_containers/coredns:v1.12.0
registry.aliyuncs.com/google_containers/etcd:3.5.21-0
registry.aliyuncs.com/google_containers/kube-apiserver:v1.33.2
registry.aliyuncs.com/google_containers/kube-controller-manager:v1.33.2
registry.aliyuncs.com/google_containers/kube-proxy:v1.33.2
registry.aliyuncs.com/google_containers/kube-scheduler:v1.33.2
registry.aliyuncs.com/google_containers/pause:3.10
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-apiserver:v4.1.3
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-console:v4.1.3
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-controller-manager:v4.1.3
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/gateway-apiserver:v1.0.2
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-extensions-museum:v1.1.3
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/kube-state-metrics:v2.12.0
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/kubectl:v1.27.12
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/kubectl:v1.27.16
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/gateway-controller-manager:v1.0.2
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/network-extension-apiserver:v1.1.0
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/network-extension-controller:v1.1.0
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/pvc-autoresizer:v0.3.1
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/snapshot-controller:v4.2.1
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/snapshotclass-controller:v0.0.1
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/storageclass-accessor:v0.2.5
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/whizard-telemetry-apiserver:v1.2.2
swr.cn-southwest-2.myhuaweicloud.com/ks/kubespheredev/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
swr.cn-southwest-2.myhuaweicloud.com/ks/prometheus-operator/prometheus-operator:v0.75.1
swr.cn-southwest-2.myhuaweicloud.com/ks/prometheus-operator/prometheus-config-reloader:v0.75.1
swr.cn-southwest-2.myhuaweicloud.com/ks/prometheus/prometheus:v2.51.2
swr.cn-southwest-2.myhuaweicloud.com/ks/prometheus/node-exporter:v1.8.1
swr.cn-southwest-2.myhuaweicloud.com/ks/brancz/kube-rbac-proxy:v0.18.0
swr.cn-southwest-2.myhuaweicloud.com/ks/curlimages/curl:7.85.0
swr.cn-southwest-2.myhuaweicloud.com/ks/grafana/grafana:10.4.1
EOF

      - name: Pull Docker images
        run: |
          while read image; do
            echo "Pulling $image"
            docker pull "$image"
          done < images.txt

      - name: Save Docker images to TAR
        run: |
          docker save $(cat images.txt | tr '\n' ' ') -o docker-images/all-images.tar

      - name: Upload TAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-tar
          path: docker-images/all-images.tar
